version: '3.6'
services:

  protes-worker:
    image: protes:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    links:
      - mongodb
      - rabbitmq
    command: bash -c "cd /app/pro_tes; celery worker -A celery_worker -E --loglevel=info"
    volumes:
      - ${PROTES_DATA_DIR:-../data/pro_tes}:/data

  protes:
    image: protes:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    links:
      - mongodb
    command: bash -c "cd /app/pro_tes; gunicorn -c config.py wsgi:app"
    volumes:
      - ${PROTES_DATA_DIR:-../data/pro_tes}:/data
    ports:
      - "7878:8080"

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    restart: unless-stopped
    links:
      - mongodb
    ports:
      - "5682:5672"

  mongodb:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
      - ${PROTES_DATA_DIR:-../data/pro_tes}/db:/data/db
    ports:
      - "27027:27017"

  flower:
    image: mher/flower:0.9
    restart: unless-stopped
    links:
      - protes-worker
    command: flower --broker=amqp://guest:guest@rabbitmq:5672// --port=5555
    ports:
      - "5565:5555"
