version: '3.6'
services:

  celery-worker-protes:
    image: protes:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    links:
      - mongo-protes
      - rabbit-protes
    command: bash -c "cd /app/pro_tes; celery worker -A celery_worker -E --loglevel=info"
    volumes:
      - ../data/pro_tes:/data

  protes:
    image: protes:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    links:
      - mongo-protes
    command: bash -c "cd /app/pro_tes; gunicorn -c config.py wsgi:app"
    volumes:
      - ../data/pro_tes:/data

  rabbit-protes:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    restart: unless-stopped
    links:
      - mongo-protes

  mongo-protes:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
      - ../data/pro_tes/db:/data/db

  flower-protes:
    image: mher/flower:0.9
    restart: unless-stopped
    links:
      - celery-worker-protes
    command: flower --broker=amqp://guest:guest@rabbit-protes:5672// --port=5555
