# General server/service settings
server:
    host: '0.0.0.0'
    port: 8080
    debug: False
    environment: production
    testing: False
    use_reloader: False

# Security settings
security:
    authorization_required: False
    jwt:
        auth_header_key: Authorization
        claim_identity: sub
        claim_issuer: iss
        claim_key_id: kid
        decode_algorithms:
          - RS256
        idp_config_jwks: jwks_uri
        idp_config_url_suffix: /.well-known/openid-configuration
        idp_config_userinfo: userinfo_endpoint
        jwt_prefix: Bearer
        validation_methods:
          - userinfo
          - public_key
        validate_with: any  # 'any' or 'all'

# Database settings
database:
    host: mongodb
    port: 27017
    name: protes-db
    task_id:
        length: 6
        charset: string.ascii_uppercase + string.digits

# Storage
storage:
    spec_dir: '/data/specs'

# Celery task queue
celery:
    broker_host: rabbitmq
    broker_port: 5672
    result_backend: 'rpc://'
    include:
        - pro_tes.tasks.tasks.submit_task

# OpenAPI specs
api:
    specs:
        - path: '20190903.d55bf88.task_execution_service.modified.swagger.yaml'
          type: 'yaml'
          strict_validation: True
          validate_responses: False # has to be False because MINIMAL view is not spec-compliant
          swagger_ui: True
          swagger_json: True
    endpoint_params:
        timeout_service_calls: 3
        timeout_task_execution: Null  # minimum: 5
        interval_polling: 2
        max_missed_heartbeats: 100

# TES service info settings
service_info:
    doc: Proxy TES for distributing tasks across a list of service TES instances
    name: proTES
    storage:
        - file:///path/to/local/storage

# TES services
tes:
    service_list:
        - 'https://csc-tesk.c03.k8s-popup.csc.fi/'
        - 'https://csc-tesk.c03.k8s-popup.csc.fi/v1/'
        - 'https://tes1.tsi.ebi.ac.uk/tes/v1/'
        - 'https://tes.tsi.ebi.ac.uk/v1/'
        - 'https://tes-dev.tsi.ebi.ac.uk/v1/'
