---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.protes.appName}}-volume
spec:
  accessModes:
    - {{ .Values.storageAccessMode }} 
  resources:
    requests:
      storage: '1Gi'
