# This workflow will build the project, lint, run tests, and build and push
# Docker images. For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build app
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  lint:
    name: Run linting
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v3
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: install requirements
        run: |
          pip install -e .
          pip install -r requirements_dev.txt
      - name: lint with flake8
        run: flake8
  test:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      PROBE_ENDPOINT: localhost:8080/ga4gh/tes/v1/ui/
    steps:
      - name: check out repository
        uses: actions/checkout@v2
      #      - name: create data directories
      #        run: mkdir -p ${HOME}/data/{db,output,tmp}
      - name: start up app
        run: docker-compose up -d --build
      - name: wait until app is up
        run: sleep 30
      - name: run health check
        run: |
          echo "${PROBE_ENDPOINT}"
          test $( \
            curl \
             -sL \
             -v \
             -o /dev/null \
             -w '%{http_code}' \
             -X GET \
             --header 'Accept: application/json' \
             "${PROBE_ENDPOINT}" \
            ) == '200' || exit 1
      - name: run integration tests
        run: pytest tests/integrationTest
#    needs: [code-style]
