---
name: Test with docker compose
on:
  push:
    branches: [ dev , feature ]
  pull_request:
    branches: [ dev ]

jobs:
  code-style:
    name: Run linting
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install requirements
        run: |
          pip install -e .
          pip install -r requirements_dev.txt
          pip install -r req
      - name: Lint with flake8
        run: flake8
  build:
    runs-on: ubuntu-latest
    needs: [code-style]
    env:
      PROBE_ENDPOINT: localhost:8080/ga4gh/tes/v1/ui/
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.7", "3.8","3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install docker-compose
        pip install -r requirements_dev.txt
        pip install -r req
    - name: Create data directories
      run: mkdir -p ${HOME}/data/{db,output,tmp}
    - name: Docker compose up
      run: docker-compose up -d --build
    - name: Sleep 30
      run: sleep 30
    - name: PROBE
      run: echo "${PROBE_ENDPOINT}"
    - name: Test
      run: |
        test $( \
          curl \
           -sL \
           -v \
           -o /dev/null \
           -w '%{http_code}' \
           -X GET \
           --header 'Accept: application/json' \
           "${PROBE_ENDPOINT}" \
          ) == '200' || exit 1
    - name: Calculate integration test coverage
      run: |
        coverage run -m pytest tests/integrationTest/test_endpoints.py -W ignore::DeprecationWarning
        coverage xml
        coverage report -m
    - name: Submit Report to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        flags: Integration Tests
        fail_ci_if_error: true
        verbose: true
