---
name: Test with docker compose
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.7", "3.8","3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pip install docker-compose
    - name: Create data directories
      run: mkdir -p ${HOME}/data/{db,output,tmp}
    - name: Docker compose up
      run: docker-compose up -d
    - name: Sleep 30
      run: sleep 30
    - name: PROBE
      run: echo "${PROBE_ENDPOINT}"
    - name: Test
      run: |
        test $( \
          curl \
           -L \
           -v \
           -o /dev/null \
           -w '%{http_code}' \
           -X GET \
           --header 'Accept: application/json' \
           "${PROBE_ENDPOINT}" \
          ) == '200' || exit 1

